### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [deniseiras/fortranMakeUtils#1]
I suggest adding topics such as `fortran`, `build`, `build-system`, `make`, `makefile`, `dependency-tree` in the About section at https://github.com/deniseiras/fortranMakeUtils.

**Comment by deniseiras** [comment]
Hi Beliavsky,

Thank you for the suggestion, I will do that!
Actually I am improving the code for threat more reserved words,
interfaces, includes and so on and generating dot files for graphics
visualization, including tests for it.

Cheers,

*Denis Eiras*





Em ter., 22 de nov. de 2022 às 13:25, Beliavsky ***@***.***>
escreveu:

**Comment by deniseiras** [comment]
Is this a pattern for About ? Could you inform some link with this information or example repositories ?

**Comment by deniseiras** [comment]
Topics were included in about section.
Also, README.md was detailed.
